apiVersion: v1
kind: Template
metadata:
  name: edi-order-services-buildtime
labels:
  template: edi-order-services-buildtime
  app: edi-order-services 
parameters:
- name: ENV_NAME
  description: environment level being created such as master,sys, qa, prd
  value: sqlserver
- name: NAMESPACE  
- name: db2datasource_url
- name: db2datasource_username
- name: db2datasource_password
- name: sqldatasource_url
- name: sqldatasource_username
- name: sqldatasource_password
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${ENV_NAME}-edi-order-services-secret
    environment: ${ENV_NAME}
  type: Opaque 
  stringData:
    db2datasource_url: ${db2datasource_url}
    db2datasource_username: ${db2datasource_username}
    db2datasource_password: ${db2datasource_password}
    sqldatasource_url: ${sqldatasource_url}
    sqldatasource_username: ${sqldatasource_username}
    sqldatasource_password: ${sqldatasource_password}

